### PR TITLE
feat: upgrade Electron from v8 to v12

### PR DESCRIPTION
**Pull request by seesemichaelj**
This PR makes the necessary changes to upgrade Electron to v12+. This ended up really only being upgrading versions of various packages. All flavors work as they did before this PR. I also ran a Linux build (not other OS's) with electron-builder and it worked fine

### CODE REVIEW

**Comment by seesemichaelj** [comment]
I'm moving this out of draft as I haven't heard back on whether or not getting Corda running with this upgrade is a priority or not (as it is nontrivial). So do note, that as-is, Corda has issues with starting the quickstart workspace on subsequent runs. Deleting the electron config folder (`~/.config/Electron`) will consistently get it to start the first time, but after that it has issues. I suspect this is due to NodeJS changes about how `child_process`'s `spawn` works. I spent 6 hours looking into it, but stopped there after deeming it non-trivial.

**Comment by superJackiee** [comment]
Amazing work result..

**Review by superJackiee — COMMENTED** [review]
amazing work result..

**Review by AstroOrbis — APPROVED** [review]
This fixes an Electron issue (electron-v8.2.1-darwin-arm64.zip doesn't exist) on MacOS m1.

**Comment by TmLev** [comment]
Is this going to be merged? 

Why am I interested: currently, I am unable to spin up Ganache application on M1 Pro. Was hoping this would fix it.

**Comment by jeffsmale90** [comment]
Thanks @seesemichaelj !

@TmLev We are working on getting Ganache-ui back up and running, and am myself dealing with the M1 build issues. I hope to have something working, at least in development, over the next weeks.

**Pull request closed without merging**
